language: node_js
notifications:
  email: daniloapromano@live.com
node_js:
  - 'node'
sudo: required
dist: xenial
services:
  - mongodb
  - xvfb
#env:
  #global:
   # - NODE_ENV: test

addons:
  chrome: stable
 # sauce_connect: true
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - npm install -g protractor
  - webdriver-manager update
  - bower install
before_script:
  - export NODE_ENV=test
  - export DISPLAY=:99.0
  - node test/data.js
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run
  #- node server & protractor config/protractor.js
