language: node_js
node_js:
  - v16.3.0
notifications:
    - daniloapromano@live.com
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - npm install -g protractor
  - bower install
before_script:
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js