# This is a basic workflow to help you get started with Actions

name: UnitTesting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 #Checkout Repo
    - uses: actions/setup-node@v1 #Setup Node
      with:
        node-version: '12'
    - name: Run Karma Tests
      run: |
        npm install
        karma start config/karma.config.js 
